export const moviesData = [
  {
    id: "1",
    title: "Beyond Earth",
    thumbnail: {
      trending: {
        small: "../assets/img/movies/beyond-earth/trending/small.jpg",
        large: "../assets/img/movies/beyond-earth/trending/large.jpg",
      },
      regular: {
        small: "../assets/img/movies/beyond-earth/regular/small.jpg",
        medium: "../assets/img/movies/beyond-earth/regular/medium.jpg",
        large: "../assets/img/movies/beyond-earth/regular/large.jpg",
      },
    },
    year: 2019,
    category: "Movie",
    rating: "PG",
    isBookmarked: false,
    isTrending: true,
  },
  {
    id: "2",
    title: "Bottom Gear",
    thumbnail: {
      trending: {
        small: "../assets/img/movies/bottom-gear/trending/small.jpg",
        large: "../assets/img/movies/bottom-gear/trending/large.jpg",
      },
      regular: {
        small: "../assets/img/movies/bottom-gear/regular/small.jpg",
        medium: "../assets/img/movies/bottom-gear/regular/medium.jpg",
        large: "../assets/img/movies/bottom-gear/regular/large.jpg",
      },
    },
    year: 2021,
    category: "Movie",
    rating: "PG",
    isBookmarked: false,
    isTrending: true,
  },
  {
    id: "3",
    title: "Undiscovered Cities",
    thumbnail: {
      trending: {
        small: "../assets/img/movies/undiscovered-cities/trending/small.jpg",
        large: "../assets/img/movies/undiscovered-cities/trending/large.jpg",
      },
      regular: {
        small: "../assets/img/movies/undiscovered-cities/regular/small.jpg",
        medium: "../assets/img/movies/undiscovered-cities/regular/medium.jpg",
        large: "../assets/img/movies/undiscovered-cities/regular/large.jpg",
      },
    },
    year: 2019,
    category: "TV Series",
    rating: "E",
    isBookmarked: false,
    isTrending: true,
  },
  {
    id: "4",
    title: "1998",
    thumbnail: {
      trending: {
        small: "../assets/img/movies/1998/trending/small.jpg",
        large: "../assets/img/movies/1998/trending/large.jpg",
      },
      regular: {
        small: "../assets/img/movies/1998/regular/small.jpg",
        medium: "../assets/img/movies/1998/regular/medium.jpg",
        large: "../assets/img/movies/1998/regular/large.jpg",
      },
    },
    year: 2021,
    category: "Movie",
    rating: "18+",
    isBookmarked: false,
    isTrending: true,
  },
  {
    id: "5",
    title: "Dark Side of the Moon",
    thumbnail: {
      trending: {
        small: "../assets/img/movies/dark-side-of-the-moon/trending/small.jpg",
        large: "../assets/img/movies/dark-side-of-the-moon/trending/large.jpg",
      },
      regular: {
        small: "../assets/img/movies/dark-side-of-the-moon/regular/small.jpg",
        medium: "../assets/img/movies/dark-side-of-the-moon/regular/medium.jpg",
        large: "../assets/img/movies/dark-side-of-the-moon/regular/large.jpg",
      },
    },
    year: 2018,
    category: "TV Series",
    rating: "PG",
    isBookmarked: true,
    isTrending: true,
  },
  {
    id: "6",
    title: "The Great Lands",
    thumbnail: {
      regular: {
        small: "../assets/img/movies/the-great-lands/regular/small.jpg",
        medium: "../assets/img/movies/the-great-lands/regular/medium.jpg",
        large: "../assets/img/movies/the-great-lands/regular/large.jpg",
      },
    },
    year: 2019,
    category: "Movie",
    rating: "E",
    isBookmarked: false,
    isTrending: false,
  },
  {
    id: "7",
    title: "The Diary",
    thumbnail: {
      regular: {
        small: "../assets/img/movies/the-diary/regular/small.jpg",
        medium: "../assets/img/movies/the-diary/regular/medium.jpg",
        large: "../assets/img/movies/the-diary/regular/large.jpg",
      },
    },
    year: 2019,
    category: "TV Series",
    rating: "PG",
    isBookmarked: false,
    isTrending: false,
  },
  {
    id: "8",
    title: "Earth’s Untouched",
    thumbnail: {
      regular: {
        small: "../assets/img/movies/earths-untouched/regular/small.jpg",
        medium: "../assets/img/movies/earths-untouched/regular/medium.jpg",
        large: "../assets/img/movies/earths-untouched/regular/large.jpg",
      },
    },
    year: 2017,
    category: "Movie",
    rating: "18+",
    isBookmarked: true,
    isTrending: false,
  },
  {
    id: "9",
    title: "No Land Beyond",
    thumbnail: {
      regular: {
        small: "../assets/img/movies/no-land-beyond/regular/small.jpg",
        medium: "../assets/img/movies/no-land-beyond/regular/medium.jpg",
        large: "../assets/img/movies/no-land-beyond/regular/large.jpg",
      },
    },
    year: 2019,
    category: "Movie",
    rating: "E",
    isBookmarked: false,
    isTrending: false,
  },
  {
    id: "10",
    title: "During the Hunt",
    thumbnail: {
      regular: {
        small: "../assets/img/movies/during-the-hunt/regular/small.jpg",
        medium: "../assets/img/movies/during-the-hunt/regular/medium.jpg",
        large: "../assets/img/movies/during-the-hunt/regular/large.jpg",
      },
    },
    year: 2016,
    category: "TV Series",
    rating: "PG",
    isBookmarked: false,
    isTrending: false,
  },
  {
    id: "11",
    title: "Autosport the Series",
    thumbnail: {
      regular: {
        small: "../assets/img/movies/autosport-the-series/regular/small.jpg",
        medium: "../assets/img/movies/autosport-the-series/regular/medium.jpg",
        large: "../assets/img/movies/autosport-the-series/regular/large.jpg",
      },
    },
    year: 2016,
    category: "TV Series",
    rating: "18+",
    isBookmarked: false,
    isTrending: false,
  },
  {
    id: "12",
    title: "Same Answer II",
    thumbnail: {
      regular: {
        small: "../assets/img/movies/same-answer-2/regular/small.jpg",
        medium: "../assets/img/movies/same-answer-2/regular/medium.jpg",
        large: "../assets/img/movies/same-answer-2/regular/large.jpg",
      },
    },
    year: 2017,
    category: "Movie",
    rating: "E",
    isBookmarked: false,
    isTrending: false,
  },
  {
    id: "13",
    title: "Below Echo",
    thumbnail: {
      regular: {
        small: "../assets/img/movies/below-echo/regular/small.jpg",
        medium: "../assets/img/movies/below-echo/regular/medium.jpg",
        large: "../assets/img/movies/below-echo/regular/large.jpg",
      },
    },
    year: 2016,
    category: "TV Series",
    rating: "PG",
    isBookmarked: false,
    isTrending: false,
  },
  {
    id: "14",
    title: "The Rockies",
    thumbnail: {
      regular: {
        small: "../assets/img/movies/the-rockies/regular/small.jpg",
        medium: "../assets/img/movies/the-rockies/regular/medium.jpg",
        large: "../assets/img/movies/the-rockies/regular/large.jpg",
      },
    },
    year: 2015,
    category: "TV Series",
    rating: "E",
    isBookmarked: true,
    isTrending: false,
  },
  {
    id: "15",
    title: "Relentless",
    thumbnail: {
      regular: {
        small: "../assets/img/movies/relentless/regular/small.jpg",
        medium: "../assets/img/movies/relentless/regular/medium.jpg",
        large: "../assets/img/movies/relentless/regular/large.jpg",
      },
    },
    year: 2017,
    category: "Movie",
    rating: "PG",
    isBookmarked: true,
    isTrending: false,
  },
  {
    id: "16",
    title: "Community of Ours",
    thumbnail: {
      regular: {
        small: "../assets/img/movies/community-of-ours/regular/small.jpg",
        medium: "../assets/img/movies/community-of-ours/regular/medium.jpg",
        large: "../assets/img/movies/community-of-ours/regular/large.jpg",
      },
    },
    year: 2018,
    category: "TV Series",
    rating: "18+",
    isBookmarked: false,
    isTrending: false,
  },
  {
    id: "17",
    title: "Van Life",
    thumbnail: {
      regular: {
        small: "../assets/img/movies/van-life/regular/small.jpg",
        medium: "../assets/img/movies/van-life/regular/medium.jpg",
        large: "../assets/img/movies/van-life/regular/large.jpg",
      },
    },
    year: 2015,
    category: "Movie",
    rating: "PG",
    isBookmarked: false,
    isTrending: false,
  },
  {
    id: "18",
    title: "The Heiress",
    thumbnail: {
      regular: {
        small: "../assets/img/movies/the-heiress/regular/small.jpg",
        medium: "../assets/img/movies/the-heiress/regular/medium.jpg",
        large: "../assets/img/movies/the-heiress/regular/large.jpg",
      },
    },
    year: 2021,
    category: "Movie",
    rating: "PG",
    isBookmarked: true,
    isTrending: false,
  },
  {
    id: "19",
    title: "Off the Track",
    thumbnail: {
      regular: {
        small: "../assets/img/movies/off-the-track/regular/small.jpg",
        medium: "../assets/img/movies/off-the-track/regular/medium.jpg",
        large: "../assets/img/movies/off-the-track/regular/large.jpg",
      },
    },
    year: 2017,
    category: "Movie",
    rating: "18+",
    isBookmarked: true,
    isTrending: false,
  },
  {
    id: "20",
    title: "Whispering Hill",
    thumbnail: {
      regular: {
        small: "../assets/img/movies/whispering-hill/regular/small.jpg",
        medium: "../assets/img/movies/whispering-hill/regular/medium.jpg",
        large: "../assets/img/movies/whispering-hill/regular/large.jpg",
      },
    },
    year: 2017,
    category: "Movie",
    rating: "E",
    isBookmarked: false,
    isTrending: false,
  },
  {
    id: "21",
    title: "112",
    thumbnail: {
      regular: {
        small: "../assets/img/movies/112/regular/small.jpg",
        medium: "../assets/img/movies/112/regular/medium.jpg",
        large: "../assets/img/movies/112/regular/large.jpg",
      },
    },
    year: 2013,
    category: "TV Series",
    rating: "PG",
    isBookmarked: false,
    isTrending: false,
  },
  {
    id: "22",
    title: "Lone Heart",
    thumbnail: {
      regular: {
        small: "../assets/img/movies/lone-heart/regular/small.jpg",
        medium: "../assets/img/movies/lone-heart/regular/medium.jpg",
        large: "../assets/img/movies/lone-heart/regular/large.jpg",
      },
    },
    year: 2017,
    category: "Movie",
    rating: "E",
    isBookmarked: true,
    isTrending: false,
  },
  {
    id: "23",
    title: "Production Line",
    thumbnail: {
      regular: {
        small: "../assets/img/movies/production-line/regular/small.jpg",
        medium: "../assets/img/movies/production-line/regular/medium.jpg",
        large: "../assets/img/movies/production-line/regular/large.jpg",
      },
    },
    year: 2018,
    category: "TV Series",
    rating: "PG",
    isBookmarked: false,
    isTrending: false,
  },
  {
    id: "25",
    title: "Dogs",
    thumbnail: {
      regular: {
        small: "../assets/img/movies/dogs/regular/small.jpg",
        medium: "../assets/img/movies/dogs/regular/medium.jpg",
        large: "../assets/img/movies/dogs/regular/large.jpg",
      },
    },
    year: 2016,
    category: "TV Series",
    rating: "E",
    isBookmarked: true,
    isTrending: false,
  },
  {
    id: "26",
    title: "Asia in 24 Days",
    thumbnail: {
      regular: {
        small: "../assets/img/movies/asia-in-24-days/regular/small.jpg",
        medium: "../assets/img/movies/asia-in-24-days/regular/medium.jpg",
        large: "../assets/img/movies/asia-in-24-days/regular/large.jpg",
      },
    },
    year: 2020,
    category: "TV Series",
    rating: "PG",
    isBookmarked: false,
    isTrending: false,
  },
  {
    id: "27",
    title: "The Tasty Tour",
    thumbnail: {
      regular: {
        small: "../assets/img/movies/the-tasty-tour/regular/small.jpg",
        medium: "../assets/img/movies/the-tasty-tour/regular/medium.jpg",
        large: "../assets/img/movies/the-tasty-tour/regular/large.jpg",
      },
    },
    year: 2016,
    category: "TV Series",
    rating: "PG",
    isBookmarked: false,
    isTrending: false,
  },
  {
    id: "28",
    title: "Darker",
    thumbnail: {
      regular: {
        small: "../assets/img/movies/darker/regular/small.jpg",
        medium: "../assets/img/movies/darker/regular/medium.jpg",
        large: "../assets/img/movies/darker/regular/large.jpg",
      },
    },
    year: 2017,
    category: "Movie",
    rating: "18+",
    isBookmarked: true,
    isTrending: false,
  },
  {
    id: "29",
    title: "Unresolved Cases",
    thumbnail: {
      regular: {
        small: "../assets/img/movies/unresolved-cases/regular/small.jpg",
        medium: "../assets/img/movies/unresolved-cases/regular/medium.jpg",
        large: "../assets/img/movies/unresolved-cases/regular/large.jpg",
      },
    },
    year: 2018,
    category: "TV Series",
    rating: "18+",
    isBookmarked: false,
    isTrending: false,
  },
  {
    id: "30",
    title: "Mission: Saturn",
    thumbnail: {
      regular: {
        small: "../assets/img/movies/mission-saturn/regular/small.jpg",
        medium: "../assets/img/movies/mission-saturn/regular/medium.jpg",
        large: "../assets/img/movies/mission-saturn/regular/large.jpg",
      },
    },
    year: 2017,
    category: "Movie",
    rating: "PG",
    isBookmarked: true,
    isTrending: false,
  },
];
